### ISSUE TITLE
google grant checkboxes unticked

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#530]
Roman:

> I just signed up in the app, but after login with my gmail account I got these errors in console:
> 
> ":information_source:[ERROR HANDLING] ErrorHandler should be used for this error ***** missedBackupQuery(FlowCrypt.GmailServiceError.providerError(Error Domain=com.google.GTLRErrorObjectDomain Code=403 "Request had insufficient authentication scopes." UserInfo={GTLRStructuredError=GTLRErrorObject 0x281c6a2e0: {code:403 errors:[1] message:"Request had insufficient authentication scopes." status:"PERMISSION_DENIED"}, NSLocalizedDescription=Request had insufficient authentication scopes.}))"
> ":information_source:[Setup][SetupInitialViewController] Changed to new state error(FlowCrypt.GmailServiceError.missedBackupQuery(FlowCrypt.GmailServiceError.providerError(Error Domain=com.google.GTLRErrorObjectDomain Code=403 "Request had insufficient authentication scopes." UserInfo={GTLRStructuredError=GTLRErrorObject 0x281c6a2e0: {code:403 errors:[1] message:"Request had insufficient authentication scopes." status:"PERMISSION_DENIED"}, NSLocalizedDescription=Request had insufficient authentication scopes.})))"

Me:

> Did you untick any of the checkboxes during oauth grant maybe?

Roman:

> No, I haven't unticked anything, just tapped "Allow"
> I restarted app and checkbox was unticked by default
> So probably Gmail needs user to manually tick checkboxes for allowing access

Me:

> Not normal - very interesting. Most users first use the browser extension, where this is not needed. I wonder if they then use the iOS app second, it's already pre-checked. Let's move this conversation to GitHub, it would be good to have it documented. I'll file an issue.

**Comment by tomholub** [comment]
How to triage:

1) create a new vanilla Gmail account. Don't use it with any other FlowCrypt app
2) try to sign up with `Continue with Gmail`
3) are the checkboxes on the grant screen checked or unchecked by default?

Then try something similar on an account where FlowCrypt was already used (or same account after doing it at least once successfully)

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/134727795-c2ea8a9f-0e46-43c9-908f-fb70791f8b19.png)

![image](https://user-images.githubusercontent.com/6306961/134727803-46a0bcab-93cf-4f9b-8184-3b84af2ce6c6.png)

**Comment by tomholub** [comment]
I suppose the scope we pass into google auth request must be wrong, or there is some other similar problem. You could compare the code to Android or browser extension, or to other apps that use Google oauth with additional scopes, and see what went wrong.

**Comment by sosnovsky** [comment]
@tomholub I tried to change full mail access scope `https://mail.google.com/` to scopes which are used in browser extension - `https://www.googleapis.com/auth/gmail.compose` and `https://www.googleapis.com/auth/gmail.modify`.
But now google auth screen shows security alert, maybe FlowCrypt app should pass some additional review before asking these permissions?
![Simulator Screen Shot - iPhone 11 - 2021-10-05 at 13 52 15](https://user-images.githubusercontent.com/1062093/136011414-09d1b891-01a2-44e3-9c84-9b249d249936.png)

**Comment by sosnovsky** [comment]
Here more information about unverified apps - https://support.google.com/cloud/answer/7454865?hl=en

**Comment by tomholub** [comment]
I think we'll have to retain the full scope - we need more permissions on mobile because it's a full-fledged mail client, unlike the browser extension which is an add-on to an existing mail client (the Gmail webmail).

I suppose the better place to look may be the Android app then - since it's similar in scope to iOS.

What is the bundle id of the app that gets built from the IDE this way? Is it `com.flowcrypt.ios.debug`? Is the team id showing `W57XRJ27NX`?

Usage also looks ok (but unsure why still limited - will check)

![image](https://user-images.githubusercontent.com/6306961/136014196-bcfa968a-38bc-45c3-a699-48b7f1dea737.png)

Scopes look ok:

![image](https://user-images.githubusercontent.com/6306961/136014606-2d15f6ba-5c0a-46b9-8adf-cb0611f2de8b.png)

I went ahead and re-submitted it for verification. Maybe that will help. At the same time I added scope for contacts: #462 #283 

Let's wait what that will bring us. Thanks for looking into this! I'll un-assign you until I have news regarding the verification.

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/136031024-e5cf0f59-14a6-414b-8f0c-1e9c01b483ff.png)

**Comment by sosnovsky** [comment]
Yes, when running app from Xcode it gets `com.flowcrypt.ios.debug` bundle id and team id is `W57XRJ27NX`

It seems I got unverified app screen because app asked for not listed scopes - `gmail.compose` and `gmail.modify`. This screen doesn't appear when we try to ask full `mail.google.com` permission. So the issue is why it's unchecked on google permissions screen, maybe some privacy measures.

I checked Android implementation and it has the same `mail.google.com` permission scope (https://github.com/FlowCrypt/flowcrypt-android/blob/e2d0dd753a82eade6af6e9060499a3979f8dc5a6/FlowCrypt/src/main/java/com/flowcrypt/email/util/google/GoogleApiClientHelper.kt#L35)

**Comment by tomholub** [comment]
I think the whole oauth setup on Google was in some sort of semi-unverified state (else why would it still have a 100 users limit). This may have effects even when we use the regular `mail.google.com` scope - maybe that's why they uncheck it automatically. Let's wait for Google to verify the oauth app completely, and then we'll re-try.

Are you encountering this also on google accounts where you already granted this before? Because on my company email, it won't bother me with this regardless of how many times I retry (I suppose because I've already done it at least once).

**Comment by sosnovsky** [comment]
The same for me - it doesn't ask me for permissions after ticking checkbox for the first time.

**Comment by tomholub** [comment]
after rebuilding from master

**Comment by sosnovsky** [comment]
Yes, warning is shown in this case.

**Comment by tomholub** [comment]
In the verified scopes we have: `.../auth/contacts`

![image](https://user-images.githubusercontent.com/6306961/137891828-96de8715-f515-4acd-94a0-8bb7fcd8fd55.png)

![image](https://user-images.githubusercontent.com/6306961/137891701-5dc63f25-09d7-4e2c-8155-488f92d4ed19.png)

but in code we use `.readonly`:

```
    var value: String {
        switch self {
        case .userInfo: return "https://www.googleapis.com/auth/userinfo.profile"
        case .mail: return "https://mail.google.com/"
        case .contacts: return "https://www.googleapis.com/auth/contacts.readonly"
        }
    }
```

Which should be strictly lower than just contacts, and therefore allowed, but let me try to remove that.

**Comment by tomholub** [comment]
I've had an observation: it seemed when only one "sensitive" scope is needed, then it will be auto-checked. Eg if only Gmail is requested, then it's checked, if only Contacts are requested, then the same.

I think Google is trying to nudge us to request one at a time. It would be possible, eg Gmail during setup and then Contacts later when searching contacts. That means Contacts would be an optional grant.

Not 100% sure though - need to test again.

**Comment by tomholub** [comment]
@sosnovsky please later try adjusting the code to not request both Gmail & Contacts at the same time.

Request Gmail (plus other small permissions) during setup.

Then request Contacts when I tap into the recipients field and don't have contacts scope yet.

Doing it this way, it should resolve the unchecked checkboxes issue.

**Comment by sosnovsky** [comment]
@tomholub I tried to remove `contacts` permission during sign up, but `mail` checkbox is still unchecked.
So probably asking only for 1 sensitive permission doesn't fix this issue.

![Simulator Screen Shot - iPhone 13 - 2021-11-15 at 14 22 38](https://user-images.githubusercontent.com/1062093/141781438-787b9681-5b39-4608-936f-b2c890ca0937.png)

**Comment by sosnovsky** [comment]
And here screenshot of login screen in another email app, it doesn't have any checkboxes - you can only `Allow` or `Cancel`

![IMG_A2CCE1FD4884-1](https://user-images.githubusercontent.com/1062093/141784586-d58b2fd1-0341-43c7-96cc-e7db2b8a978f.jpeg)

**Comment by tomholub** [comment]
> @tomholub I tried to remove contacts permission during sign up, but mail checkbox is still unchecked.
So probably asking only for 1 sensitive permission doesn't fix this issue.

I see. We'll eventually do this either way (so that users don't have to worry about privacy

> And here screenshot of login screen in another email app, it doesn't have any checkboxes - you can only Allow or Cancel

They are not asking for the three other permissions above. When you're at it, could you see which ones you can remove, while it would still remain working? (we just need to be able to pull idToken)

**Comment by sosnovsky** [comment]
I checked their google auth URL and it contains the same `userinfo.profile` and `userinfo.email` permissions as Flowcrypt, but they aren't shown on the auth screen. 

![IMG_AF735DCDBCF4-1](https://user-images.githubusercontent.com/1062093/141786392-f4603f94-0991-4932-a8a8-d4a501eb3e6a.jpeg)

**Comment by tomholub** [comment]
Normally, it wouldn't be shown if it was already granted to them. In FlowCrypt it's the same. Try unticking both checkboxes during setup, then proceeding.

From Google's perspective, you've granted the two/three id grants.

Now only add Gmail. It should not have a checkbox (that's what I've seen, I think).

**Comment by sosnovsky** [comment]
> Normally, it wouldn't be shown if it was already granted to them. In FlowCrypt it's the same. Try unticking both checkboxes during setup, then proceeding.
> 
> From Google's perspective, at that point you've granted the two/three id grants.
> 
> Now only add Gmail. It should not have a checkbox (that's what I've seen, I think).
> 
> (is it possible that Spark has separate "login - id permissions only" and "grant - advanced permissions" steps? either way, we could do that, if it helps)

I tried to sign into Spark for the first time with this account, so previously I didn't check any checkboxes, it was my first auth there.
And I think they have only one permissions step (shown on screenshot) - I just tapped "Add new account", entered my Google credentials and then this screen was shown (with `mail` and `calendar` permissions)

**Comment by tomholub** [comment]
Got it. Please try, with contacts removed as above, to login with gmail unchecked, then follow the ui to do it again. The three should be gone, and gmail should hopefully not have a checkbox.

**Comment by sosnovsky** [comment]
Initial auth
![Simulator Screen Shot - iPhone 13 - 2021-11-15 at 15 20 10](https://user-images.githubusercontent.com/1062093/141788955-9385181f-a7dc-4a00-b70c-53b115947005.png)

Next login screen
![Simulator Screen Shot - iPhone 13 - 2021-11-15 at 15 20 21](https://user-images.githubusercontent.com/1062093/141788952-4f27361c-e445-43c4-80fd-c1c304691628.png)

Second auth screen
![Simulator Screen Shot - iPhone 13 - 2021-11-15 at 15 20 39](https://user-images.githubusercontent.com/1062093/141788943-e94a3945-fd8b-43b1-a936-dd447d1f16c2.png)

**Comment by sosnovsky** [comment]
I think on the first auth screen we should show 3 `user info` permissions + `mail`.

Then app should check if `mail` permission was checked, if no - show screen with message "Connect your inbox on the next screen" and after tap on "Continue" button it'll show auth screen with only `mail` permission:
![Simulator Screen Shot - iPhone 13 - 2021-11-15 at 15 20 39](https://user-images.githubusercontent.com/1062093/141791671-5dd23c6e-97e5-4b8a-98e7-5e0c45fc5850.png)

And when user tries to compose new mail and taps "Recipient" field then app should show alert "If you want to search through your contacts please allow access on the next screen" with `Allow` and `Not now` buttons. Tapping `Allow` will open google auth screen with only `contacts` permission. For the case when user taps `Not now` we can probably add `Allow contacts access` button somewhere on the Settings screen.

**Comment by tomholub** [comment]
Yup, that would do

**Comment by sosnovsky** [comment]
@tomholub what do you think about frequency of `Contacts access permission` popup - should we show it only 1 time or after each app restart?

**Comment by tomholub** [comment]
On browser extension, I list it on the bottom of contact search results. That's unobtrusive, so it can be there every time. See https://github.com/FlowCrypt/flowcrypt-browser/pull/4121#issuecomment-970819949

**Comment by sosnovsky** [comment]
Yeah, looks good 👍
Then I'll show alert only 1 time when user taps on recipient field and later it'll be shown only on the bottom of contact search results.

**Comment by tomholub** [comment]
> Yeah, looks good +1 Then I'll show alert only 1 time when user taps on recipient field and later it'll be shown only on the bottom of contact search results.

That's a good compromise, but now you'll have to store somewhere in storage that you already showed it?

**Comment by sosnovsky** [comment]
Yes, it can be stored in `UserDefaults`, similar to how it's implemented here https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Controllers/Compose/ComposeViewController.swift#L1072

By the way, do we still need `showScopeAlertIfNeeded` function from the link above? As `shouldRenewToken` always return `false` in current code https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Controllers/Compose/ComposeViewController.swift#L1097

**Comment by tomholub** [comment]
I don't know - I'll let you use your judgement freely when refactoring.
